# Generated by Django 4.2.1 on 2023-05-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shows',
            name='year',
            field=models.IntegerField(),
        ),
    ]
